### ISSUE TITLE
(feature request summary)

### ISSUE THREAD

**Issue by puppykiwi** [NuruProgramming/Nuru#54]
### Describe the feature

The string "ni" could be used to represent the comparison operator "==" while the string "si" could be used to represent "!=".

This is similar to python's use of "is" and "is not" respectively

### Use Case

This is not urgent nor is it terribly important but more swahili in my editor is better :)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

version 0.5.1

### Environment details (OS name and version, etc.)

Arch Linux

**Comment by AvicennaJr** [comment]
Its an interesting proposal. Let me discuss it with the community.

**Comment by kibali-cell** [comment]
Great feature! 👍🏿🔥

**Comment by AvicennaJr** [comment]
Closing this for now, might reopen in future.
